import type { Product } from "./types"

export const products: Product[] = [
  // Fruits & Vegetables
  {
    id: "f1",
    name: "Organic Bananas",
    description: "Sweet and nutritious organic bananas",
    price: 149,
    image: "/images/banana.jpeg",
    category: "fruits-vegetables",
    unit: "Bunch (5-7 pieces)",
  },
  {
    id: "f2",
    name: "Fresh Strawberries",
    description: "Juicy, ripe strawberries picked at peak freshness",
    price: 379,
    image: "/images/strawberries.jpeg",
    category: "fruits-vegetables",
    unit: "1 lb package",
    sale: true,
  },
  {
    id: "f3",
    name: "Avocados",
    description: "Perfectly ripe Hass avocados",
    price: 189,
    image: "/images/avacado.jpeg",
    category: "fruits-vegetables",
    unit: "Each",
  },
  {
    id: "f4",
    name: "Organic Spinach",
    description: "Fresh organic spinach leaves",
    price: 259,
    image: "/images/spinach.jpeg",
    category: "fruits-vegetables",
    unit: "10 oz bag",
  },

  // Dairy & Eggs
  {
    id: "d1",
    name: "Organic Whole Milk",
    description: "Fresh organic whole milk from grass-fed cows",
    price: 379,
    image: "/images/milk.jpeg",
    category: "dairy-eggs",
    unit: "1 liter",
  },
  {
    id: "d2",
    name: "Large Brown Eggs",
    description: "Farm-fresh large brown eggs from free-range chickens",
    price: 419,
    image: "/images/eggs.jpeg",
    category: "dairy-eggs",
    unit: "Dozen",
  },
  {
    id: "d3",
    name: "Sharp Cheddar Cheese",
    description: "Aged sharp cheddar cheese",
    price: 529,
    image: "/images/cheese.jpeg",
    category: "dairy-eggs",
    unit: "200g block",
  },
  {
    id: "d4",
    name: "Greek Yogurt",
    description: "Plain Greek yogurt, high in protein",
    price: 299,
    image: "/images/yogurt.jpeg",
    category: "dairy-eggs",
    unit: "500g container",
  },

  // Bakery
  {
    id: "b1",
    name: "Artisan Sourdough Bread",
    description: "Freshly baked artisan sourdough bread",
    price: 459,
    image: "/images/sourdough_bread.jpeg",
    category: "bakery",
    unit: "1 loaf (400g)",
  },
  {
    id: "b2",
    name: "Chocolate Chip Cookies",
    description: "Freshly baked chocolate chip cookies",
    price: 349,
    image: "/images/cookies.jpeg",
    category: "bakery",
    unit: "12 count package",
    sale: true,
  },
  {
    id: "b3",
    name: "Blueberry Muffins",
    description: "Moist blueberry muffins baked daily",
    price: 459,
    image: "/images/muffins.jpeg",
    category: "bakery",
    unit: "4 count package",
  },
  {
    id: "b4",
    name: "Whole Wheat Bagels",
    description: "Hearty whole wheat bagels",
    price: 379,
    image: "/images/bagels.jpeg",
    category: "bakery",
    unit: "6 count package",
  },

  // Snacks
  {
    id: "s1",
    name: "Mixed Nuts",
    description: "Premium blend of roasted nuts",
    price: 599,
    image: "/images/mixednuts.jpeg",
    category: "snacks",
    unit: "300g bag",
  },
  {
    id: "s2",
    name: "Potato Chips",
    description: "Crispy kettle-cooked potato chips",
    price: 259,
    image: "/images/potato chips.jpeg",
    category: "snacks",
    unit: "200g bag",
  },
  {
    id: "s3",
    name: "Dark Chocolate Bar",
    description: "72% cacao dark chocolate bar",
    price: 299,
    image: "/images/chocolate.jpeg",
    category: "snacks",
    unit: "100g bar",
  },
  {
    id: "s4",
    name: "Trail Mix",
    description: "Energy-boosting trail mix with dried fruits and nuts",
    price: 419,
    image: "/images/trail mix.jpeg",
    category: "snacks",
    unit: "400g bag",
  },

  // Beverages
  {
    id: "bv1",
    name: "Orange Juice",
    description: "100% pure squeezed orange juice, not from concentrate",
    price: 379,
    image: "/images/orange juice.jpeg",
    category: "beverages",
    unit: "1 liter bottle",
  },
  {
    id: "bv2",
    name: "Cold Brew Coffee",
    description: "Smooth cold brew coffee",
    price: 349,
    image: "/images/cold brew coffee.jpeg",
    category: "beverages",
    unit: "750ml bottle",
  },
  {
    id: "bv3",
    name: "Sparkling Water",
    description: "Refreshing sparkling water with natural flavors",
    price: 459,
    image: "/images/sparkling water.jpeg",
    category: "beverages",
    unit: "8 pack, 330ml cans",
    sale: true,
  },
  {
    id: "bv4",
    name: "Green Tea",
    description: "Organic green tea bags",
    price: 329,
    image: "/images/green tea.jpeg",
    category: "beverages",
    unit: "20 count box",
  },

  // Household Items
  {
    id: "h1",
    name: "Paper Towels",
    description: "Absorbent and durable paper towels",
    price: 679,
    image: "/images/paper towel.jpeg",
    category: "household",
    unit: "6 roll pack",
  },
  {
    id: "h2",
    name: "Dish Soap",
    description: "Plant-based dish soap, gentle on hands",
    price: 299,
    image: "/images/dish soap.jpeg",
    category: "household",
    unit: "750ml bottle",
  },
  {
    id: "h3",
    name: "Laundry Detergent",
    description: "Eco-friendly laundry detergent",
    price: 979,
    image: "/images/laundry detergent.jpeg",
    category: "household",
    unit: "1.5 liter bottle",
  },
  {
    id: "h4",
    name: "Trash Bags",
    description: "Durable kitchen trash bags",
    price: 569,
    image: "/images/trash bags.jpeg",
    category: "household",
    unit: "30 count box",
  },
]
